### PR TITLE
Authorization

### PR DESCRIPTION
**Pull request by I159**
Basic auth added to the list of mocked parameters. Also, the code formatted with [Black](https://github.com/psf/black)

### CODE REVIEW

**Comment by I159** [comment]
Btw, is it ok to use Py 2.x incompatible code? I found that on the Pypi no mentions of 2.x versions.

**Comment by keredson** [comment]
can you resubmit w/o the code reformatting?

**Comment by keredson** [comment]
nm, c/ped manually in https://github.com/keredson/boddle/commit/74413e4c5b39a37ea1694fab07b459ccd2998390.  thanks!

**Comment by keredson** [comment]
released in v0.2.9

**Pull request closed without merging**
